set nocompatible
source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/mswin.vim
behave mswin
set fileencodings=utf-8,iso-8859-2,windows-1250
let maplocalleader = "," 
imap <LocalLeader>< &lt;
imap <LocalLeader>> &gt;
imap <LocalLeader>& &amp;
imap <LocalLeader>n &nbsp;
imap <C-t> <></><Esc>5hdiwp3lpT>i
set wildmode=longest,list
set background=dark
colorscheme darkblue
set guioptions=-r
set guioptions=-T
set guioptions=-M
set enc=utf-8
set rop=type:directx,geom:1,taamode:1
